replicaCount: 3

image:
  repository: compucomm/emp-service
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false

global:
  secret:
    name: ccoms-secrets
  env:
    secrets:
      DB_USER: "mongo"
      DB_PASSWD: "mongo123"
      DATABASE: "ccoms"
    normal:
      CCOMS_DATABASE_PORT: 27017
      CCOMS_CONFIG_PORT: 8888
      CCOMS_EMP_PORT: 8080
      CCOMS_DEPT_PORT: 8081
      CCOMS_ORG_PORT: 8082
      CCOMS_PROXY_PORT: 8111
      app.profile: dev
  profile: dev

