apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-import-dump-script
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  setup.sh: |
    #!/bin/sh

    dump_location="/dump"
    echo "Checking dump availability"

    if [ ! -d $dump_location ]
    then
      echo "Dump directory is not preset"
      exit 0
    fi
 
    echo "Dump location found"

    echo "Finding out master node information"
    master_node_info=$(mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 --quiet --eval "db.isMaster()['"'primary'"']")
    while [ $? -ne 0 -a ! -z $master_node_info ]
    do
      master_node_info=$(mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 --quiet --eval "db.isMaster()['"'primary'"']")
      echo "Master node info- $master_node_info"
    done

    master_node=$(echo | awk -F: '{ print $1}')
    echo "Importing mongo db dump on - $master_node"
     
    echo "Importing dump on master node"
    until mongorestore --host $master_node --port 27017 --db {{ .Values.global.env.secrets.DATABASE }} $dump_location/ccoms/
    do
      echo "Waiting for importing dump"
      sleep 5
    done
    
    echo "DB has been imported succesfully..."