apiVersion: v1
kind: Service
metadata:
   name: {{ template "name" . }}
   labels:
      app: {{ template "name" . }}
spec:
   ports:
   -  port: {{ .Values.global.env.normal.DATABASE_PORT }}
      protocol: TCP
   selector:
      role: {{ .Values.global.env.normal.ROLE }}
      environment: {{ .Values.global.profile }}
   clusterIP: None
