replicaCount: 5

image:
  repository: mongo
  tag: 4.2
  pullPolicy: Always

global:
  secret:
    name: ccoms-secrets
  profile: dev
  env:
    secrets:
      DB_USER: "mongo"
      DB_PASSWD: "mongo123"
      DATABASE: "ccoms"

ingress:
  enabled: false

db_secret:
  name: db-secrets
  
env:
  db_secrets:
    MONGO_INITDB_ROOT_USERNAME: "admin"
    MONGO_INITDB_ROOT_PASSWORD: "admin123"
    MONGO_INITDB_DATABASE: "admin"
  normal:
    DATABASE_PORT: 27017
    ROLE: mongo

## Creating namespace
createReleaseNamespace: true

#####  Mongo Values ##########
mongodb:
  enabled: true

## Persist data to a persistent volume
persistence:
  enabled: true
  storageClass: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  size: 400Mi
  pvs: 5
  mountPath: /data/db
  ### TGoogle Compute Engine persistent disk, an NFS share, or an Amazon Elastic Block Store volume
  ### hostpath is for local and nfs is for nfs 
  ## network 
  networkResource: hostPath
  ## provide below value in case you are using nfs network resource, otherwise below value will not be used
  server: 
  # annotations: {}
  # subPath: ""
  # existingClaim: