{{- if .Values.mongodb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-import-dump"
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    component: mongodb
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
      - name: dump-import-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - 'sh'
        - '-c'
        - 'sh /scripts/setup.sh'
        volumeMounts:
        - name: mongodb-import-dump-script
          mountPath: "/scripts"
        - name: mongodb-import-dump
          mountPath: "/dump"
      volumes:
      - name: mongodb-import-dump-script
        configMap:
          name: {{ template "name" . }}-import-dump-script
      - name: mongodb-import-dump
      {{- if (eq "hostPath" .Values.persistence.networkResource) }}
        hostPath:
      {{- end }}
      {{- if (eq "nfs" .Values.persistence.networkResource) }}
        nfs:
          server: {{ .Values.persistence.server }}
      {{- end }}    
          path: /u02/mongo_dump    
{{- end }}